apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "novanet.fullname" . }}-cni
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novanet.labels" . | nindent 4 }}
data:
  10-novanet.conflist: |
    {
      "cniVersion": "1.0.0",
      "name": "novanet",
      "plugins": [
        {
          "type": "novanet-cni",
          "agentSocket": "/run/novanet/cni.sock"
        }
      ]
    }
